### ISSUE TITLE
seed.sh file doesn't properly load the database

### ISSUE THREAD

**Issue by jaboto** [dhis2/docker-compose#11]
I don't fully understand how this tool works. However, when using providing a seed db file it seems to not import it properly.

This is due to the database not being cleaned up before the seed.sh is executed and the container seems to have already some data there. Therefore, I think it is recommended to empty the database before executing the import.

```
echo "Deleting DB and Importing '$file'..."
	$DOCKER_COMPOSE exec -e PGPASSWORD=$dbPass -T $dbContainer psql -h $dbContainer --dbname $dbName --username $dbUser -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public;"

    if [ ${file: -7} == ".sql.gz" ]
      then
```

**Comment by varl** [comment]
Hi @jaboto 

Thanks for the report. We usually don't use Docker Compose directly so this repo needs to be updated a bit. The main thing here is that we have to use `seed.sh` before using `start.sh` since DHIS2 does things to the database when booting up, and our "seed" file is actually a full database dump.

What we usually do is use the [d2 cluster](https://cli.dhis2.nu/#/commands/d2-cluster) command to manage a local DHIS2 cluster (e.g. dhis2 + database):

```
d2 cluster up master \
    --channel dev \
    --db-version dev \
    --seed
```

I will look into making it so that if we pass in the `--seed` flag (and run the `seed.sh` script) we first clean the db, then seed it, automatically. It seems like this is a common issue people are running into.

**Comment by jaboto** [comment]
Thanks @varl :)

**Comment by amcgee** [comment]
Closing this issue - created https://jira.dhis2.org/browse/CLI-39 to track the `--drop-db` feature.

(@varl we should probably disable gh issues here?)
